tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-tertiary": "#ffeff0",
              "surface-container": "#cfecff",
              "surface-container-lowest": "#ffffff",
              "primary-fixed-dim": "#00c0ea",
              "tertiary": "#b60051",
              "tertiary-dim": "#a00047",
              "secondary-dim": "#5819db",
              "outline-variant": "#87b3cd",
              "inverse-surface": "#001019",
              "outline": "#507c94",
              "surface-bright": "#eff8ff",
              "on-tertiary-fixed-variant": "#770033",
              "inverse-on-surface": "#77a3bc",
              "secondary": "#652fe7",
              "on-secondary": "#f7f0ff",
              "on-surface-variant": "#346178",
              "primary-container": "#00cffc",
              "on-error-container": "#570008",
              "surface-tint": "#00647b",
              "surface-container-high": "#c2e8ff",
              "tertiary-container": "#ff8fa9",
              "primary": "#00647b",
              "on-secondary-fixed": "#3b00a0",
              "tertiary-fixed": "#ff8fa9",
              "surface-container-highest": "#b5e3ff",
              "on-background": "#003346",
              "on-secondary-container": "#5000d2",
              "on-error": "#ffefee",
              "on-primary-fixed-variant": "#004a5c",
              "surface-container-low": "#e2f3ff",
              "background": "#eff8ff",
              "on-primary": "#e2f6ff",
              "on-primary-container": "#004050",
              "on-surface": "#003346",
              "surface-dim": "#9fdcff",
              "error": "#b31b25",
              "surface-variant": "#b5e3ff",
              "surface": "#eff8ff",
              "inverse-primary": "#00cffc",
              "on-tertiary-container": "#66002b",
              "primary-dim": "#00576c",
              "secondary-fixed-dim": "#cabaff",
              "error-dim": "#9f0519",
              "tertiary-fixed-dim": "#ff769b",
              "on-primary-fixed": "#002a35",
              "on-secondary-fixed-variant": "#591bdc",
              "secondary-fixed": "#d8caff",
              "on-tertiary-fixed": "#380014",
              "primary-fixed": "#00cffc",
              "error-container": "#fb5151",
              "secondary-container": "#d8caff"
      },
      "borderRadius": {
              "DEFAULT": "1rem",
              "lg": "2rem",
              "xl": "3rem",
              "full": "9999px"
      },
      "spacing": {},
      "fontFamily": {
              "headline": ["Manrope"],
              "body": ["Inter"],
              "label": ["Inter"]
      }
    },
  },
}
